/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-12-04 02:06:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.luna.saltfish.dbHandle.UserHandle;
import com.luna.saltfish.dbHandle.GoodsHandle;
import com.luna.saltfish.constant.*;
import com.luna.saltfish.vo.*;
import com.luna.saltfish.tools.*;
import java.util.*;
import java.text.*;
import com.luna.saltfish.servlet.*;

public final class info_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.luna.saltfish.constant");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.luna.saltfish.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.luna.saltfish.tools");
    _jspx_imports_packages.add("com.luna.saltfish.servlet");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.luna.saltfish.dbHandle.UserHandle");
    _jspx_imports_classes.add("com.luna.saltfish.dbHandle.GoodsHandle");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
/*
物品详情页，包含详情和操作按钮
*/
      out.write('\n');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
            + path + "/";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/head.jsp", out, false);
      out.write("\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("    <title>物品详情</title>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        function toLogin(isLogin) {\n");
      out.write("            if (!isLogin) {\n");
      out.write("                window.location.href = \"user/login.jsp?login-info=\" + \"请先登录\";\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function collect(goodsId, isLogin) {\n");
      out.write("            if (isLogin) {\n");
      out.write("                collectRequest = new XMLHttpRequest();\n");
      out.write("                collectRequest.onreadystatechange = function () {\n");
      out.write("                    // 已经收藏readyState=4\n");
      out.write("                    if ((collectRequest.readyState == 4) && (collectRequest.status == 200)) {\n");
      out.write("                        if (collectRequest.responseText == \"success\") {\n");
      out.write("                            document.getElementById(\"collectButton\").innerHTML = \"==已收藏==\";\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("                collectRequest.open(\"GET\", \"CollectServlet?goodsId=\" + goodsId + \"&t=\" + Math.random(), true);\n");
      out.write("                collectRequest.send();\n");
      out.write("            } else {\n");
      out.write("                window.location.href = \"user/login.jsp?login-info=\" + \"请先登录\";\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("        $(document).ready(function () {\n");
      out.write("            let searchParams = new URLSearchParams(window.location.search);\n");
      out.write("            let goodsId = searchParams.get('goodsId');\n");
      out.write("            collectRequest = new XMLHttpRequest();\n");
      out.write("            collectRequest.onreadystatechange = function () {\n");
      out.write("                // 已经收藏readyState=4\n");
      out.write("                if ((collectRequest.readyState == 4) && (collectRequest.status == 200)) {\n");
      out.write("                    if (collectRequest.responseText == \"success\") {\n");
      out.write("                        document.getElementById(\"collectButton\").innerHTML = \"已收藏\";\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            collectRequest.open(\"GET\", \"CheckCollectServlet?goodsId=\" + goodsId + \"&t=\" + Math.random(), true);\n");
      out.write("            collectRequest.send();\n");
      out.write("\n");
      out.write("            ShoppingRequest = new XMLHttpRequest();\n");
      out.write("            ShoppingRequest.onreadystatechange = function () {\n");
      out.write("                // 已经收藏readyState=4\n");
      out.write("                if ((collectRequest.readyState == 4) && (collectRequest.status == 200)) {\n");
      out.write("                    if (collectRequest.responseText == \"success\") {\n");
      out.write("                        document.getElementById(\"addCastButton\").innerHTML = \"已加入购物车\";\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            ShoppingRequest.open(\"GET\", \"CheckShoppingServlet?goodsId=\" + goodsId + \"&t=\" + Math.random(), true);\n");
      out.write("            ShoppingRequest.send();\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        function shoppingCart(isLogin, goodsNum, goodsId) {\n");
      out.write("\n");
      out.write("            if (isLogin) {\n");
      out.write("                xmlShop = new XMLHttpRequest();\n");
      out.write("                xmlShop.onreadystatechange = function () {\n");
      out.write("                    if ((xmlShop.readyState == 4) && (xmlShop.status == 200)) {\n");
      out.write("                        if (xmlShop.responseText == \"success\") {\n");
      out.write("                            document.getElementById(\"goodsNum\").innerHTML = (parseInt(document.getElementById(\"goodsNum\").innerHTML) + 1).toString();\n");
      out.write("                            document.getElementById(\"addCastButton\").innerHTML = \"已加入购物车\";\n");
      out.write("                        } else {\n");
      out.write("                            document.getElementById(\"addCastButton\").innerHTML = \"Sorry,你可能重复添加了！\";\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("                xmlShop.open(\"GET\", \"ShoppingCartServlet?goodsId=\" + goodsId + \"&t=\" + Math.random(), true);\n");
      out.write("                xmlShop.send();\n");
      out.write("            } else {\n");
      out.write("                window.location.href = \"user/login.jsp?login-info=\" + \"请先登录\";\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/header.jsp", out, true);
      out.write("\n");
      out.write("    ");

        int goodsId = Integer.parseInt(request.getParameter("goodsId"));

        Integer goodsNum = 0;
        GoodsHandle goodsHandle = new GoodsHandle();
        UserHandle userHandle = new UserHandle();
        Goods good = goodsHandle.findById(goodsId);
        if (good == null) {
            out.print("<div class=\"alert alert-danger\" role=\"alert\">" + "没有这个物品！，请返回并检查来源页" + "</div>");
            return;
        }
        boolean isLogin = LoginVerify.isLogin(request);
        pageContext.setAttribute("good", good);
        User Procuteuser = userHandle.findById(good.getProducterId());
        pageContext.setAttribute("Procuteuser", Procuteuser);
        int typeId = good.getTypeId();
        String typeName = "";
        switch (typeId) {
            case 6:
                typeName = "其他";
                break;
            case 1:
                typeName = "书籍";
                break;
            case 2:
                typeName = "生活用品";
                break;
            case 5:
                typeName = "体育";
                break;
            case 3:
                typeName = "衣装";
                break;
            case 4:
                typeName = "电子";
                break;
        }
        Date date = good.getCreatDate();
        SimpleDateFormat myFmt = new SimpleDateFormat("yyyy年MM月dd日 HH时mm分");
        String dateStr = myFmt.format(date);
    
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-10 col-md-offset-1\">\n");
      out.write("                <div class=\"panel panel-info\">\n");
      out.write("                    <div class=\"panel-heading\">\n");
      out.write("                        ");

                            out.println("<span style=\"text-align:center;font-size:16px;\" class=\"center-block\">物品详情</span>");

                        
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"panel-body\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-5\">\n");
      out.write("                                <img title=\"右键查看原图\" class=\"info-img\" src=\"");
      out.print(good.getImage());
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-7 info-goods\">\n");
      out.write("                                <p>\n");
      out.write("                                <h3 class=\"info-goods-name\"></h3>\n");
      out.write("                                <p>\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${good.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                                </p>\n");
      out.write("                                <p>\n");
      out.write("                                    <br/>类型：<a target=\"_blank\"\n");
      out.write("                                               href=\"");
      out.print(basePath );
      out.write("index.jsp?ceta=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${good.getTypeId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.print(typeName );
      out.write("\n");
      out.write("                                </a><br/>\n");
      out.write("                                    <br/>\n");
      out.write("                                </p>\n");
      out.write("                                <p>\n");
      out.write("                                    价格：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${good.getPrice()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br/>\n");
      out.write("                                    <br/>\n");
      out.write("                                </p>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <p>\n");
      out.write("                                    发布者：\n");
      out.write("                                    <a target=\"_blank\"\n");
      out.write("                                       href=\"user/personal.jsp?tab=info&userId=");
      out.print(Procuteuser.getId());
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Procuteuser.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("                                    (联系:<a href=\"mailto:");
      out.print(Procuteuser.getEmail());
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Procuteuser.getEmail()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                                </a>\n");
      out.write("                                    或\n");
      out.write("                                    <a target=\"_blank\"\n");
      out.write("                                       href=\"user/personal.jsp?tab=mess&handle=write&toemail=");
      out.print(Procuteuser.getEmail() );
      out.write("%20==>%20");
      out.print(Procuteuser.getName());
      out.write("\">站内信</a>)\n");
      out.write("                                    <br/> <br/>\n");
      out.write("                                </p>\n");
      out.write("                                <p>\n");
      out.write("                                    发布时间：");
      out.print(dateStr );
      out.write("\n");
      out.write("                                    <br/> <br/>\n");
      out.write("                                </p>\n");
      out.write("                                <p class=\"info-goods-content\">\n");
      out.write("                                    物品说明：");
      out.print(good.getContent().replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("\n", "<br />") );
      out.write("\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- 确认购买区域 -->\n");
      out.write("                        <script type=\"text/javascript\">\n");
      out.write("                            $(document).ready(function () {\n");
      out.write("                                $(\"#buy\").click(function () {\n");
      out.write("                                    $(\".buy-confirm\").show(200);\n");
      out.write("                                });\n");
      out.write("                            });\n");
      out.write("                        </script>\n");
      out.write("                        <div style=\"display:none;\" class=\"buy-confirm\">\n");
      out.write("                            <hr/>\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-8 col-md-offset-2\">\n");
      out.write("                                    <div class=\"panel panel-info\">\n");
      out.write("                                        <div class=\"panel-heading\">\n");
      out.write("                                            <span class=\"center-block\"\n");
      out.write("                                                  style=\"text-align:center;font-size:15px;\">确定购买</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"panel-body\">\n");
      out.write("                                            <p>\n");
      out.write("                                                请输入给卖家的附加消息，然后点击 \"确定\" 按钮，我们将会通知卖家。\n");
      out.write("                                            </p>\n");
      out.write("                                            ");

                                                User user = (User) session.getAttribute(UserLoginConstant.LOGIN_USER);
                                                int userId = 0;
                                                if (user != null)
                                                    userId = user.getId();
                                            
      out.write("\n");
      out.write("                                            <form action=\"OrderCheckServlet?goodsId=");
      out.print(request.getParameter("goodsId"));
      out.write("&userId=");
      out.print(userId);
      out.write("\"\n");
      out.write("                                                  method=\"post\">\n");
      out.write("                                                <div class=\"form-group\">\n");
      out.write("                                                    <textarea class=\"form-control\" name=\"message-to-seller\"\n");
      out.write("                                                              id=\"message-to-seller\"></textarea>\n");
      out.write("                                                </div>\n");
      out.write("                                                <button type=\"submit\" class=\"pull-left btn btn-default\">确认购买</button>\n");
      out.write("                                            </form>\n");
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- end of 确认购买区域 -->\n");
      out.write("\n");
      out.write("                        <!-- 提示消息 -->\n");
      out.write("                        ");

                            if (request.getParameter("info") != null) {
                        
      out.write("\n");
      out.write("                        <div class=\"alert alert-warning\">");
      out.print(request.getParameter("info") );
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        ");
}
      out.write("\n");
      out.write("\n");
      out.write("                        <hr/>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <button id=\"collectButton\" onclick=\"collect(");
      out.print(good.getId());
      out.write(',');
      out.print(isLogin );
      out.write(")\"\n");
      out.write("                                        type=\"button\"\n");
      out.write("                                        class=\"center-block btn btn-default\">收藏此物品\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <button type=\"button\" id=\"addCastButton\"\n");
      out.write("                                        class=\"center-block btn btn-default\"\n");
      out.write("                                        onclick=\"shoppingCart(");
      out.print(isLogin );
      out.write(',');
      out.print(goodsNum );
      out.write(',');
      out.print(good.getId());
      out.write(")\">加入购物车\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-4\">\n");
      out.write("                                <button ");
      out.print(good.getStates() == 2 ? "" : "disabled=\"disabled\"" );
      out.write(" id=\"buy\"\n");
      out.write("                                                                                                   type=\"button\"\n");
      out.write("                                                                                                   class=\"center-block btn btn-default\"\n");
      out.write("                                                                                                   onclick=\"toLogin(");
      out.print(isLogin );
      out.write(")\">\n");
      out.write("                                    ");

                                        if (good.getStates() != 2) {
                                            out.print("[不可用]已被购买或未通过审核");
                                        } else {
                                            out.print("立即购买");
                                        }
                                    
      out.write("\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");

    userHandle.close();
    goodsHandle.close();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
