/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-12-04 01:24:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.luna.saltfish.vo.*;
import com.luna.saltfish.constant.*;
import com.luna.saltfish.tools.*;
import javax.servlet.http.HttpSession;
import com.luna.saltfish.dbHandle.*;

public final class personal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.luna.saltfish.constant");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.luna.saltfish.dbHandle");
    _jspx_imports_packages.add("com.luna.saltfish.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.luna.saltfish.tools");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write('\n');

    Boolean isMe = false;
    Boolean isLogin = LoginVerify.isLogin(request);
    User me = null;
    User user = null;
    Integer userId = 0;
    if (request.getParameter("userId") != null && request.getParameter("userId").length() != 0) {
        UserHandle userHandle = new UserHandle();
        userId = Integer.parseInt(request.getParameter("userId"));
        user = userHandle.findById(userId);
        userHandle.close();
    }

    if (isLogin) {
        me = (User) session.getAttribute(UserLoginConstant.LOGIN_USER);
        if ((userId != 0 && me.getId() == user.getId()) || userId == 0) {
            isMe = true;
            user = me;
            request.setAttribute("isMe", true);
        }
    } else {
        request.getRequestDispatcher("../user/login.jsp?login-info=" + java.net.URLEncoder.encode("你应该先登录，之后才可查看自己或其他人的个人信息页", "UTF-8")).forward(request, response);
        return;
    }

    String tab = request.getParameter("tab");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/head.jsp", out, false);
      out.write("\n");
      out.write("    <title>用户中心 - salt-fish</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/header.jsp", out, false);
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-3\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <div class=\"list-group\">\n");
      out.write("                            <div class=\"list-group-item personal-main-info\">\n");
      out.write("\n");
      out.write("                                <img class=\"img-rounded img-personal-main-info\"\n");
      out.write("                                     src=\"");
      out.print(user.getImg() );
      out.write("\"/>\n");
      out.write("                                <div class=\"row detail-goods text-muted\">姓名：");
      out.print(user.getName() );
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row detail-goods text-muted\">邮箱：");
      out.print(user.getEmail() );
      out.write("\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            <a href=\"user/personal.jsp?tab=info&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("                               class=\"list-group-item ");
      out.print(tab.equals("info")?"active":"" );
      out.write("\">\n");
      out.write("                                个人信息</a>\n");
      out.write("\n");
      out.write("                            ");

                                if (isMe) {
                            
      out.write("\n");
      out.write("                            ");

                                if (LoginVerify.isAdmin(request)) {
                            
      out.write("\n");
      out.write("\n");
      out.write("                            <a href=\"user/personal.jsp?tab=auditing&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("                               class=\"list-group-item ");
      out.print(tab.equals("auditing")?"active":"" );
      out.write("\">\n");
      out.write("                                物品审核</a>\n");
      out.write("                            ");
}
      out.write("\n");
      out.write("                            <a href=\"user/personal.jsp?tab=mess&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("                               class=\"list-group-item ");
      out.print(tab.equals("mess")?"active":"" );
      out.write("\">\n");
      out.write("                                站内消息</a>\n");
      out.write("                            <a href=\"user/personal.jsp?tab=shopcart&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("                               class=\"list-group-item ");
      out.print(tab.equals("shopcart")?"active":"" );
      out.write("\">\n");
      out.write("                                购物车</a>\n");
      out.write("                            <a href=\"user/personal.jsp?tab=history&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("                               class=\"list-group-item ");
      out.print(tab.equals("history")?"active":"" );
      out.write("\">\n");
      out.write("                                购买历史</a>\n");
      out.write("                            <a href=\"user/personal.jsp?tab=pushed&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("                               class=\"list-group-item ");
      out.print(tab.equals("pushed")?"active":"" );
      out.write("\">\n");
      out.write("                                我发布的</a>\n");
      out.write("                            <a href=\"user/personal.jsp?tab=push&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("                               class=\"list-group-item ");
      out.print(tab.equals("push")?"active":"" );
      out.write("\">\n");
      out.write("                                发布商品</a>\n");
      out.write("                            <a href=\"user/personal.jsp?tab=like&pn=1&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("                               class=\"list-group-item ");
      out.print(tab.equals("like")?"active":"" );
      out.write("\">\n");
      out.write("                                收藏夹 </a>\n");
      out.write("                            <!-- 并不需要设置页\n");
      out.write("\t\t\t\t\t\t\t<a href=\"user/personal.jsp?tab=setting&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"list-group-item ");
      out.print(tab.equals("setting")?"active":"" );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t设置</a>\n");
      out.write("\t\t\t\t\t\t\t-->\n");
      out.write("                            ");
} else {
      out.write("\n");
      out.write("                            <a href=\"user/personal.jsp?tab=pushed&userId=");
      out.print(user.getId() );
      out.write("\"\n");
      out.write("                               class=\"list-group-item ");
      out.print(tab.equals("pushed")?"active":"" );
      out.write("\">\n");
      out.write("                                他发布的商品</a>\n");
      out.write("                            ");
}
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-8\">\n");
      out.write("                ");
if (tab.equals("push")) {
      out.write("\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/personal/push.jsp", out, false);
      out.write("\n");
      out.write("                ");
} else if (tab.equals("info")) {
      out.write("\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/personal/info.jsp", out, false);
      out.write("\n");
      out.write("                ");
} else if (tab.equals("auditing")) {
      out.write("\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/personal/auditing.jsp", out, false);
      out.write("\n");
      out.write("                ");
} else if (tab.equals("shopcart")) {
      out.write("\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/personal/shopcart.jsp", out, false);
      out.write("\n");
      out.write("                ");
} else if (tab.equals("like")) {
      out.write("\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/personal/like.jsp", out, false);
      out.write("\n");
      out.write("                ");
} else if (tab.equals("mess")) {
      out.write("\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/personal/mess.jsp", out, false);
      out.write("\n");
      out.write("                ");
} else if (tab.equals("pushed")) {
      out.write("\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/personal/pushed.jsp", out, false);
      out.write("\n");
      out.write("                ");
} else if (tab.equals("history")) {
      out.write("\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/personal/history.jsp", out, false);
      out.write("\n");
      out.write("                ");
}
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../site/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
